### ISSUE TITLE
Example of Intercepting Undo & Redo for text fields

### ISSUE THREAD

**Issue by brainkim** [samthor/undoer#2]
Hi! Thanks for publishing library! I’m currently investigating native undo/redo for contenteditables and I was intrigued by this library and the writeup. I was wondering if you had any success implementing the strategy described in the section “Intercepting Undo & Redo for text fields” (https://dev.to/chromiumdev/-native-undo--redo-for-the-web-3fl3#intercepting-undo-amp-redo-for-text-fields).

I’ve done a little bit of experimentation and it seems like `document.execCommand("undo")` triggers additional input events, which we have to filter for. It also seems like we have to be careful to perform any DOM mutations after the `execCommand` fires, because undoing will sometimes mess with those changes. I’m thinking that a fully robust solution might require a little bit more effort, maybe including some hacks with `beforeinput` events, level 1 input events properties, or maybe `queueMicrotask`/`requestAnimationFrame`.

In any case, if you have any concrete examples of using this library to override an input or contenteditable‘s undo entries I would be super interested to see it!

**Comment by samthor** [comment]
It's been a while since I wrote that article but I think that section was probably the least developed and I certainly don't still have any examples I built myself.

I think the thing to discover is how long the 'undo' exec takes: immediately? a microtask? does it complete within `requestAnimationFrame`? If it's any one of those very simple options, then changing the inner content of an editable should be fine at that point. If it's not, well, ....

I'm also concerned, on re-reading, that calling `document.execCommand("undo")` programatically could just let the user _redo_ right after that. I vaguely remember that mucking with the DOM/input field content might cancel that ability though.

**Comment by brainkim** [comment]
> I think the thing to discover is how long the 'undo' exec takes: immediately? a microtask? does it complete within requestAnimationFrame?

As far as I can tell, all `execCommand()` calls finish synchronously. The problem I discovered was that `execCommand()` will dispatch a second `input` event synchronously, leading to a confusing situation where you are somehow in the same `input` event listener at multiple points of the call stack. This can lead to `document.execCommand("undo")` being called more times than there are undoable items for a page, which is okay in Chrome, but in Safari will (unfortunately) cause previously closed tabs to be reopened, because the people who designed Safari thought this was good behavior for browser undo 😅 I remember trying to filter out events based on the `InputEvent.inputType` property in the `input` handler, but I think I ran into other problems. For instance, Safari seems to not let you undo certain edits like pasting HTML into an editable, unless it happens in another event loop tick.

> I'm also concerned, on re-reading, that calling document.execCommand("undo") programatically could just let the user redo right after that.

From my understanding, the undoer algorithm should theoretically blow away the browser’s redo stack, because we are working on the hidden input and therefore adding new edits.

I think one of the reasons I was experimenting with microtasks and animation frames is that undoing an input, blurring it, focusing a hidden input, replacing its contents with `execCommand()`, and finally refocusing and restoring the selection of the old input is somewhat expensive. As far as I can tell, all of these operations seem to require layout validation, so they can take up a huge chunk of the CPU budget for keystrokes (~25ms before things start to feel sluggish, especially when holding down keys).

Anyways, I was mostly just curious if there was an example implementation I was missing. I see that one of your dependents (https://github.com/shanewholloway/web-lite-code-editor) seems to have an implementation of the undo stuff, which I might investigate.

This is definitely a rabbit hole which only insane people like myself would venture down, so please feel free to close the issue if it’s out of scope for the project. Thanks again for publishing this library!

**Comment by brainkim** [comment]
~~Just some late night experimentation. This seems to be the magical incantation that will undo all inputs consistently in Safari without reopening closed tabs.~~ Doesn’t always work for pastes.

```ts
let frame;
let undoing = false;
let inputs = 0;
this.addEventListener("input", (ev) => {
  if (undoing) {
    return;
  }

  inputs++;
  if (frame != null) {
    cancelAnimationFrame(frame);
  }

  frame = requestAnimationFrame(() => {
    while (inputs > 0) {
      try {
        undoing = true;
        document.execCommand("undo");
        inputs--;
      } finally {
        undoing = false;
      }
    }
  });
});
```

**Comment by samthor** [comment]
Great! Well, sorry it still has issues. Paste can be detected. The more events you're detecting though 😬

**Comment by brainkim** [comment]
Closing for housekeeping purposes. My latest thoughts are that `beforeinput` events have semi-reliable undo/redo event detection and prevention in the latest browsers, and this strategy degrades gracefully.

@samthor Thanks for the responses!
